
const satztypenliste = [
  "Absatz",
  "Abschnitt",
  "Adresse",
  "Algorithmus",
  "Alle",
  "Artikel",
  "Aufzählung",
  "Benutzer",
  "Dateipfad",
  "Details",
  "Erbfolge",
  "Gruppe",
  "Hierarchie",
  "Kapitel",
  "Kausalitätskette",
  "Linkkette",
  "Liste",
  "Manuskript",
  "Negativtaggruppe",
  "Objektattribute",
  "Route",
  "Satz",
  "Satztyp",
  "Schritte",
  "Suchkombination",
  "Synonyme",
  "Taggruppe",
  "URL",
  "UrsacheWirkung",
  "Vererbungsreihe",
  "Voraussetzungskette",
  "Wortkombination",
]

module.exports = {satztypenliste};